version: 2
discovery:
  allowed-hostnames:
    - localhost
  network-idle-timeout: 750
snapshot:
  widths:
    - 375
    - 1280
  min-height: 1024
  percy-css: |
    .percy-hide { display: none !important; }
    